import express from "express";
import url from 'url'
import db from "./database/connection.js"

const app = express();

app.get('/users', (req, res) => {
    const select = db.prepare('SELECT id, name FROM users');

    let users = select.all()

    for (let user of users) {
        //code generated by gemini. A url is generated to get to the path of a specific user
        user.details = `${req.protocol}://${req.get('host')}/users/${user.id}`
    }
    res.json(users);
})

app.get('/users/:id', async (req, res) => {
    const selectUser = db.prepare('select * from users where id=? ');
    const id = req.params.id
    console.log(id)
    const user = await selectUser.get(id);



    res.json(user);
})

app.listen(8000, () => {
    console.log("API draait nu!");
})