import express from "express";
import db from "./database/connection.js"

const app = express();

/**
 * 
 * @param {Request} req Request used to get the protocol and the host of the site
 * @param {string} route Route required for the url (after the host)
 * @param {number, string} index Can be used to get a specific index in a route, standard an empty string
 * @returns A url in form of a string
 */
const generateUrl = (req, route, index = '') => {
    return `${req.protocol}://${req.get('host')}/${route}/${index}`
}

app.get('/users', (req, res) => {
    const select = db.prepare('SELECT id, name FROM users');

    let users = select.all()

    for (let user of users) {
        //code generated by gemini. A url is generated to get to the path of a specific user
        user.details = generateUrl(req, 'users', user.id)
    }
    res.json(users);
})

app.get('/users/:id', async (req, res) => {
    const selectUser = db.prepare('select * from users where id=? ');
    const id = req.params.id
    console.log(id)
    const user = await selectUser.get(id);

    res.json(user);
})

app.listen(8000, () => {
    console.log("API draait nu!");
})