import { validationResult } from 'express-validator';
import createDatabase from '../../database/connection.js'
import {generateUrl} from "../functions/url.js"

const deviceController = {}

deviceController.get_all = async (req, res) => {
    const db = createDatabase();
    const select = db.prepare('SELECT id, name FROM devices');

    let devices =  await select.all()
    for (let device of devices) {
        //code generated by gemini. A url is generated to get to the path of a specific device
        device.details = generateUrl(req, 'devices', device.id)
    }

    db.close()

    res.json(devices);
} 

deviceController.get_device = async (req, res) => {
    const db = createDatabase();
    const selectDevice = db.prepare('select * from devices where id=? ');
    const id = req.params.id
    const device = await selectDevice.get(id);
    db.close();

    if (!device) {
        return res.json({notfound: "This device doesn't appear to exist"})
    }

    res.json(device);
}

deviceController.create = async (req, res) => {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
        return res.json({errors: errors.array()})
    }

    const {name, release_date, description} = req.body

    const db = createDatabase();

    const nameCheck = db.prepare('select * from devices where name=?')

    const rows = nameCheck.get(name)

    if (rows) {
        return res.json({errors: "This device's name is already in use"})
    }

    const insertDevice = db.prepare("insert into devices(name, release_date, description) values(?, ?, ?)")
    insertDevice.run(name, release_date, description)

    return res.json({succes: "Device succesfully added"})
}

deviceController.update = async (req, res) => {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
        return res.json({errors: errors.array()})
    }

    const body = req.body

    //This means that only the ID would have been sendt
    if (Object.keys(body).length == 1) {
        return res.json({errors: "Please give some values to update"})
    }

    const {id, name, release_date, description} = body

    const db = createDatabase();
    const selectDevice = db.prepare('select * from devices where id=? ');
    const device = await selectDevice.get(id);

    if (!device) {
        return res.json({notfound: "This device doesn't appear to exist"})
    }

    let changes = ""

    const changedValues = []

    if (name) {
        changes += " name=?,"
        changedValues.push(name)
    }
    if (release_date) {
        changes += " release_date=?,"
        changedValues.push(release_date)
    }
    if (description) {
        changes += " description=?,"
        changedValues.push(description)
    }

    changes = changes.substring(0, changes.length - 1)

    const changeDevice = db.prepare(`update devices set ${changes} where id=?`)
    changedValues.push(id)
    changeDevice.run(...changedValues)

    const changed_device = generateUrl(req, "devices", id)

    return res.json({succes: "Device succesfully changed", changed_device : generateUrl(req, "devices", id)})
}

deviceController.delete = async (req, res) => {
    const db = createDatabase();
    const id = req.params.id

    const checkDevice = db.prepare('select * from devices where id=? ');
    const rows = await checkDevice.get(id);


    if (!rows) {
        return res.json({notfound: "This device doesn't appear to exist"})
    }

    const deleteAction = db.prepare('delete from devices where id=?');
    console.log(deleteAction)
    deleteAction.run(id)

    db.close()
    
    return res.json({succes: "device succesfully deleted"})
}

export default deviceController