import { validationResult } from 'express-validator';
import createDatabase from '../../database/connection.js'
import {generateUrl} from "../functions/url.js"

const deviceController = {}

deviceController.get_all = async (req, res) => {
    const db = createDatabase();
    const select = db.prepare('SELECT id, name FROM devices');

    let devices =  await select.all()
    for (let device of devices) {
        //code generated by gemini. A url is generated to get to the path of a specific user
        device.details = generateUrl(req, 'devices', device.id)
    }

    db.close()

    res.json(devices);
} 

deviceController.get_device = async (req, res) => {
    const db = createDatabase();
    const selectDevice = db.prepare('select * from devices where id=? ');
    const id = req.params.id
    const device = await selectDevice.get(id);
    db.close();

    if (!device) {
        return res.json({errors: "This device doesn't appear to exist"})
    }

    res.json(device);
}

deviceController.create = async (req, res) => {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
        return res.json({errors: errors.array()})
    }

    return res.json({message, "This function isn't ready yet"})
}

export default deviceController