import createDatabase from '../../database/connection.js'

/**
 * 
 * @param {Request} req Request used to get the protocol and the host of the site
 * @param {string} route Route required for the url (after the host)
 * @param {number, string} index Can be used to get a specific index in a route, standard an empty string
 * @returns A url in form of a string
 */
const generateUrl = (req, route, index = '') => {
    return `${req.protocol}://${req.get('host')}/${route}/${index}`
}

const userController = {};

userController.get_all = async (req, res) => {
    const db = createDatabase();
    const select = db.prepare('SELECT id, name FROM users');

    let users =  await select.all()
    for (let user of users) {
        //code generated by gemini. A url is generated to get to the path of a specific user
        user.details = generateUrl(req, 'users', user.id)
    }
    res.json(users);
}

userController.get_user = async (req, res) => {
    const db = createDatabase();
    const selectUser = db.prepare('select * from users where id=? ');
    const id = req.params.id
    const user = await selectUser.get(id);

    res.json(user);
}
export default userController