import { validationResult } from 'express-validator';
import createDatabase from '../../database/connection.js'
import {generateUrl} from "../functions/url.js"

const userController = {};

userController.get_all = async (req, res) => {
    const index = req.params.id != null ? req.params.id : 1

    const db = createDatabase();
    const select = db.prepare('SELECT id, concat(first_name, \' \', name) as name FROM users limit 5 offset ' + (index- 1) * 5);

    let users =  await select.all()

    if (users.length == 0) {
        return res.json({notfound: "No users were found on this page"})
    }

    for (let user of users) {
        //code generated by gemini. A url is generated to get to the path of a specific user
        user.details = generateUrl(req, 'users', user.id)
    }

    const select_amount = db.prepare("select count(*) as amount from users" )
    const amount = await select_amount.all()[0].amount;

    const response = {
        users: users
    }

    //Generates a next line and previous line. Next line is calculated using the amount of rows in the table
    if (amount / 5 > index) {
        response.next_line = generateUrl(req, 'users/page', parseInt(index) + 1)
    }
    if (index > 1) response.previous_line = generateUrl(req, 'users/page', parseInt(index) - 1)

    db.close()

    res.json(response);
}

userController.get_user = async (req, res) => {
    const db = createDatabase();
    const selectUser = db.prepare('select * from users where id=? ');
    const id = req.params.id
    const user = await selectUser.get(id);
    db.close();

    if (!user) {
        return res.json({notfound: "This user doesn't appear to exist"})
    }

    res.json(user);
}

userController.create = async (req,res) => {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
        return res.json({errors: errors.array()})
    }

    const {first_name, name, email, birthday, about_me} = req.body

    const db = createDatabase();

    const mailCheck = db.prepare('select * from users where email=?')

    const rows = mailCheck.get(email)

    if (rows) {
        return res.json({errors: "This mail is already in use"})
    }

    const insertUser = db.prepare("insert into users(first_name, name, email, birthday, about_me) values (?, ?, ?, ?, ?)")

    const response = await insertUser.run(first_name, name, email, birthday, about_me)

    return res.json({succes: "Account succesfully added!"});
}

userController.change = async (req, res) => {
    const errors = validationResult(req);

    if (!errors.isEmpty()) {
        return res.json({errors: errors.array()})
    }  

    const body = req.body
    //This means that only the ID would have been sendt
    //https://www.freecodecamp.org/news/check-if-an-object-is-empty-in-javascript/
    if (Object.keys(body).length == 1) {
        return res.json({errors: "Please give some values to update"})
    }

    const {id, name, email, birthday, about_me} = body;

    let changes = ""

    const changedValues = []

    if (name) {
        changes += " name=?,"
        changedValues.push(name)
    }
    if (email) {
        changes += " email=?,"
        changedValues.push(email)
    }
    if (birthday) {
        changes += " birthday=?,"
        changedValues.push(birthday)
    }
    if (about_me) {
        changes += " about_me=?,"
        changedValues.push(about_me)
    }


    changes = changes.substring(0, changes.length - 1)

    const db = createDatabase();

    const userCheck = db.prepare('select * from users where id=? ');
    const rows = await userCheck.get(id);


    if (!rows) {
        return res.json({notfound: "This user doesn't appear to exist"})
    }

    const userChange = db.prepare(`Update users set ${changes} where id=?`)

    changedValues.push(id);

    userChange.run(...changedValues)

    db.close();

    return res.json({
        succes: "User succesfully changed!",
        changed_user: generateUrl(req, "users", id)
    })
}

userController.delete = async (req, res) => {
    const db = createDatabase();
    const id = req.params.id

    const userCheck = db.prepare('select * from users where id=? ');
    const rows = await userCheck.get(id);


    if (!rows) {
        return res.json({notfound: "This user doesn't appear to exist"})
    }

    const deleteAction = db.prepare('delete from users where id=?');
    deleteAction.run(id)

    db.close()
    
    return res.json({succes: "account succesfully deleted"})
}

export default userController